languaje: node_js
node_js:
  - 13

install:
  - npm install

test:
  - npm run test

deploy:
  provider: heroku
  api_key: 34ec8ede-a497-4d11-8dd6-7d803b5a53f5
  app:
    develop: fiuba-taller-2-web-admin-st
    master: fiuba-taller-2-web-admin
