export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const IS_ACTIVE_LOADING = 'IS_ACTIVE_LOADING'
export const IS_ACTIVE_YES = 'IS_ACTIVE_YES'
export const IS_ACTIVE_NO = 'IS_ACTIVE_NO'
